# Target.action

# Request
# interfaces/msg/Taskspace target_pose
float64[4] target_pose [0.0, 0.0, 0.0, 0.0]
---
# Result definition
bool success
string message

---
# Feedback definition
float32 distance_to_target
string current_status