master:
  node_id: 7
  sync_period: 10000 # us 

slave_1:
  dcf: "605.0141.01-L.eds"
  node_id: 1
  
slave_2:
  dcf: "605.0141.01-L.eds"
  node_id: 2

slave_3:
  dcf: "605.0141.01-L.eds"
  node_id: 3

slave_4:
  dcf: "605.0141.01-L.eds"
  node_id: 4