"""Visualize CTR dataset .mat files generated by scripts/dataset_gen/data_gen.py.

This script intentionally contains its own plotting function (copied/adapted style)
instead of reusing the function from data_gen.py, so you can edit it independently.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.gridspec import GridSpec
from scipy.io import loadmat

from matplotlib.gridspec import GridSpec
import os
pgf_with_latex = {
	"pgf.texsystem": "pdflatex",
	"text.usetex": True,
	"font.family": "serif",
	"font.serif": [],
	"font.sans-serif": [],
	"font.monospace": [],
	"axes.labelsize": 8,
	"font.size": 8,
	"legend.fontsize": 6,
	"xtick.labelsize": 8,
	"ytick.labelsize": 8,
	"grid.color": "lightgray",
	"grid.linewidth": 0.5,
	"pgf.preamble": r"\usepackage[utf8x]{inputenc}, \usepackage[T1]{fontenc}",
	"axes.titlesize": 8,
}
plt.rcParams.update(pgf_with_latex)

def _squeeze_numeric(arr: np.ndarray) -> np.ndarray:
	"""Convert MATLAB arrays to squeezed float NumPy arrays."""
	return np.asarray(arr).squeeze()


def load_dataset_mat(mat_path: Path) -> dict[str, np.ndarray]:
	"""Load expected arrays from a dataset .mat file."""
	data = loadmat(mat_path)

	required_keys = ["q", "f"]
	for key in required_keys:
		if key not in data:
			raise KeyError(f"Missing '{key}' in {mat_path}.")

	q = _squeeze_numeric(data["q"])
	f = _squeeze_numeric(data["f"])
	sl1 = _squeeze_numeric(data["sl1"]) if "sl1" in data else None

	if q.ndim != 2 or q.shape[1] < 6:
		raise ValueError(f"Expected q with shape (N, 6+), got {q.shape}.")
	if f.ndim != 2 or f.shape[1] < 3:
		raise ValueError(f"Expected f with shape (N, 3+), got {f.shape}.")

	return {"q": q[:, :6], "f": f[:, :3], "s": sl1}


def plot_3d_collocation(
	q_coll: np.ndarray,
	f_coll: np.ndarray,
	s_coll: np.ndarray | None = None,
	figure_name: str = "Collocation_3D",
	out_path: Path | None = None,
) -> None:
    """Plot 3D scatter of collocation-like points.

    This function is deliberately local to this file so you can customize it
    without affecting data generation code.
    """
    if s_coll is None:
        # Fallback color scale if no arc-length-like variable is available.
        s_coll = np.linspace(0.0, 1.0, q_coll.shape[0], dtype=float).reshape(-1, 1)
    else:
        s_coll = np.asarray(s_coll).reshape(-1, 1)

    fig = plt.figure(figsize=(6, 2.5), num=figure_name)
    gs = GridSpec(1, 3, figure=fig, width_ratios=[1, 1, 2])
    axs = []
    axs.append(fig.add_subplot(gs[0, 0]))
    axs.append(fig.add_subplot(gs[0, 1]))
    axs.append(fig.add_subplot(gs[0, 2], projection="3d"))

    c = 5

    axs[0].scatter(q_coll[::c, 1]*1e3, q_coll[::c, 0]*1e3, s=1, c=s_coll[::c, 0])
    axs[0].set_xlabel(r"$\beta_2$ [mm]")
    axs[0].set_ylabel(r"$\beta_1$ [mm]")
    axs[0].set_title(r"Data Points $\beta$")
    axs[0].set_aspect("equal", adjustable="datalim")

    axs[1].scatter(q_coll[::c, 4], q_coll[::c, 3], s=1, c=s_coll[::c, 0])
    axs[1].set_xlabel(r"$\alpha_2$ [rad]")
    axs[1].set_ylabel(r"$\alpha_1$ [rad]")
    axs[1].set_title(r"Data Points $\alpha$")
    axs[1].set_aspect("equal", adjustable="datalim")

    axs[2].scatter(f_coll[::c, 0], f_coll[::c, 1], f_coll[::c, 2], s=1, c=s_coll[::c, 0], cmap="viridis",)
    axs[2].set_xlabel(r"$f_x$ [N]")
    axs[2].set_ylabel(r"$f_y$ [N]")
    axs[2].set_zlabel(r"$f_z$ [N]")
    axs[2].set_title(r"Data Points $f$")

    fig.subplots_adjust(left=0.1, right=0.90, bottom=0.2, top=0.9, wspace=0.2)
    plt.draw()
    plt.pause(0.1)

    if out_path is not None:
        out_path.parent.mkdir(parents=True, exist_ok=True)
        plt.savefig(out_path, format="png", dpi=600)
        print(f"Saved figure to '{out_path}'.")

    plt.show(block=True)


def main() -> None:
	data_root = Path(__file__).resolve().parent
	dataset_name = "ctr_v5.6.1"
	mat_path = (data_root / dataset_name / "data.mat").resolve()

	if not mat_path.exists():
		raise FileNotFoundError(f"Could not find .mat file: {mat_path}")

	loaded = load_dataset_mat(mat_path)
	q_coll = loaded["q"]
	f_coll = loaded["f"]
	s_coll = loaded["s"]

	out_path = mat_path.parent / "sampled_q_3D_visualizer.png"

	print(f"Loaded: {mat_path}")
	print(f"q shape: {q_coll.shape}, f shape: {f_coll.shape}")
	if s_coll is not None:
		print(f"s shape: {np.asarray(s_coll).shape}")
	else:
		print("s (sl1) not found in .mat; using index-based color scale.")

	plot_3d_collocation(
		q_coll=q_coll,
		f_coll=f_coll,
		s_coll=s_coll,
		figure_name=f"{mat_path.parent.name} - Collocation_3D",
		out_path=out_path,
	)


if __name__ == "__main__":
	main()
